[build]
  publish = "."
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[redirects]]
  from = "/apply"
  to = "/#interesse"
  status = 200

[[redirects]]
  from = "/solliciteren"
  to = "/#interesse" 
  status = 200

[[redirects]]
  from = "/video"
  to = "/#video"
  status = 200
